

DROP TABLE DISCOGRAFICA CASCADE CONSTRAINT;
DROP TABLE ESTUDIO_REC CASCADE CONSTRAINT;
DROP TABLE MAQUETADOR CASCADE CONSTRAINT;
DROP TABLE MANAGER CASCADE CONSTRAINT;
DROP TABLE VINILO CASCADE CONSTRAINT;
DROP TABLE FORMATO CASCADE CONSTRAINT;
DROP TABLE ARTISTA CASCADE CONSTRAINT;
DROP TABLE ALBUM CASCADE CONSTRAINT;
DROP TABLE TEMA CASCADE CONSTRAINT;
DROP TABLE EMISORA CASCADE CONSTRAINT;
DROP TABLE EXITOS CASCADE CONSTRAINT;
DROP TABLE SINGLE CASCADE CONSTRAINT;
DROP TABLE MIEMBRO CASCADE CONSTRAINT;
DROP TABLE CLIENTE CASCADE CONSTRAINT;
DROP TABLE COMPRA CASCADE CONSTRAINT;
DROP TABLE REFERENCIA CASCADE CONSTRAINT;


CREATE TABLE DISCOGRAFICA(
  NOMBRE_DISCOG VARCHAR(30) NOT NULL,
  TELEFONO NUMBER(15) NOT NULL,
  CONSTRAINT PK_NOMBRE_DISCOG PRIMARY KEY(NOMBRE_DISCOG),
  CONSTRAINT UK_TEL_DISCOG UNIQUE(TELEFONO),
  CONSTRAINT CHK_TELF_DISCOG  CHECK (TELEFONO > 99999999)
);

CREATE TABLE ESTUDIO_REC(
  NOMBRE_REC VARCHAR(60) NOT NULL,
  DIRECCION VARCHAR(80) NOT NULL,
  NOMBRE_TEC VARCHAR(30) NOT NULL,
  APELLIDO1_TEC VARCHAR(20) NOT NULL,
  APELLIDO2_TEC VARCHAR(20),
  CONSTRAINT PK_NOMBRE_REC PRIMARY KEY (NOMBRE_REC),
  CONSTRAINT UK_DIR_REC UNIQUE (DIRECCION)
);

CREATE TABLE MAQUETADOR(
  EMPRESA VARCHAR(30) NOT NULL,
  DIRECCION VARCHAR(80) NOT NULL,
  FOTOGRAFO VARCHAR(80),
  DIBUJANTE VARCHAR(80),
  MAQUETADOR VARCHAR(50),
  CONSTRAINT PK_EMPRESA PRIMARY KEY (EMPRESA),
  CONSTRAINT UK_DIR_MAQ UNIQUE (DIRECCION)
);

CREATE TABLE MANAGER(
  TELEFONO NUMBER(15) NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  APELLIDO1 VARCHAR(30) NOT NULL,
  APELLIDO2 VARCHAR (30),
  CONSTRAINT PK_CONTACTO_MNG PRIMARY KEY (TELEFONO),
  CONSTRAINT CHK_TELF_MNG CHECK (TELEFONO > 99999999)
);

CREATE TABLE VINILO(
  ISVN NUMBER(8) NOT NULL,
  DISCOGRAFICA_FK VARCHAR(30) NOT NULL,
  ESTUDIO_REC_FK VARCHAR(60) NOT NULL,
  MAQ_PORT_FK VARCHAR(30) NOT NULL,
  MAQ_CONTR_FK VARCHAR(30) NOT NULL,
  MANAGER_FK NUMBER(15) NOT NULL,
  CONSTRAINT PK_ISVN PRIMARY KEY (ISVN),
  CONSTRAINT FK_DISCOGRAFICA FOREIGN KEY(DISCOGRAFICA_FK)
  REFERENCES DISCOGRAFICA,
  CONSTRAINT FK_ESTUDIO_REC FOREIGN KEY(ESTUDIO_REC_FK)
  REFERENCES ESTUDIO_REC,
  CONSTRAINT FK_MAQ_PORT FOREIGN KEY (MAQ_PORT_FK)
  REFERENCES MAQUETADOR,
  CONSTRAINT FK_MAQ_CONT FOREIGN KEY (MAQ_CONTR_FK)
  REFERENCES MAQUETADOR,
  CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_FK)
  REFERENCES MANAGER,
  CONSTRAINT LONG_ISVN_VINILO  CHECK (ISVN > 9999999)
);


CREATE TABLE FORMATO(
  ISVN_PFK NUMBER(8) NOT NULL,
  FORMATO VARCHAR(4) NOT NULL,
  VELOCIDAD NUMBER(2) NOT NULL,
  AGUJERO NUMBER(2) NOT NULL,
  COPIAS_LANZ NUMBER(10) NOT NULL,
  COPIAS_TOTAL NUMBER (10),
  COLOR VARCHAR(15) NOT NULL,
  CONSTRAINT PK_ISVN_FORMATO PRIMARY KEY (ISVN_PFK),
  CONSTRAINT FK_ISVN FOREIGN KEY (ISVN_PFK)
  REFERENCES VINILO (ISVN) ON DELETE CASCADE
);

CREATE TABLE ARTISTA (
  NOMBRE_ART VARCHAR(50) NOT NULL,
  NACIONALIDAD VARCHAR(15) NOT NULL,
  IDIOMA VARCHAR(15) NOT NULL,
  CONSTRAINT PF_NOMBRE_ART PRIMARY KEY (NOMBRE_ART)
);

CREATE TABLE ALBUM(
  NOMBRE_ALBUM VARCHAR(50) NOT NULL,
  ISVN_FK NUMBER(8) NOT NULL,
  FECHA_LANZ DATE,
  ARTISTA_FK VARCHAR(50) NOT NULL,
  CONSTRAINT PK_ALBUM PRIMARY KEY(NOMBRE_ALBUM, ISVN_FK),
  CONSTRAINT FK_ISVN_ALBUM FOREIGN KEY (ISVN_FK)
  REFERENCES VINILO ON DELETE CASCADE,
  CONSTRAINT FK_ARTISTA_ALB FOREIGN KEY (ARTISTA_FK)
  REFERENCES ARTISTA ON DELETE CASCADE
);

CREATE TABLE TEMA(
  TITULO VARCHAR(60) NOT NULL,
  ISVN_FK NUMBER(8) NOT NULL,
  NOMBRE_ALBUM_FK VARCHAR(50) NOT NULL,
  CARA CHAR(1) NOT NULL,
  PISTA NUMBER(1) NOT NULL,
  DURACION CHAR(5) NOT NULL,
  AUTOR VARCHAR(80) NOT NULL,
  CONSTRAINT PK_TEMA PRIMARY KEY(TITULO, ISVN_FK),
  CONSTRAINT FK_ISVN_TEMA FOREIGN KEY(ISVN_FK, NOMBRE_ALBUM_FK)
  REFERENCES ALBUM (ISVN_FK, NOMBRE_ALBUM) ON DELETE CASCADE,
  CONSTRAINT CHK_CARA_TEMA CHECK (CARA IN ('A', 'B', 'C', 'D')),
  CONSTRAINT CHK_TIEMPO_MIN CHECK (60>TO_NUMBER(SUBSTR(DURACION,1,2))),
  CONSTRAINT CHK_TIMEPO_SEG CHECK (60>TO_NUMBER(SUBSTR(DURACION,4,5))),
  CONSTRAINT CHK_TIEMPO_SIMBOLO CHECK ((SUBSTR(DURACION,3) IN ':'))
);

CREATE TABLE EMISORA (
  NOMBRE_EMI VARCHAR(25) NOT NULL,
  DIRECCION VARCHAR(60) NOT NULL,
  URL VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  TELEFONO NUMBER(8) NOT NULL,
  CONSTRAINT PK_NOMBRE_EMI PRIMARY KEY(NOMBRE_EMI),
  CONSTRAINT UK_DIR_EMI UNIQUE (DIRECCION),
  CONSTRAINT UK_URL UNIQUE (URL),
  CONSTRAINT UK_EMAIL UNIQUE (EMAIL),
  CONSTRAINT UK_TEL_EMI UNIQUE (TELEFONO),
  CONSTRAINT CHK_EMAIL_VALIDO_EMI CHECK (
    EMAIL LIKE '%@%.%' AND
    EMAIL NOT LIKE '@%' AND
    EMAIL NOT LIKE '%@%@%'),
  CONSTRAINT URL_VALIDO CHECK (URL LIKE '%.%'),
  CONSTRAINT CHK_TELF_EMI CHECK (TELEFONO > 99999999)
);


CREATE TABLE EXITOS(
  TITULO_FK VARCHAR(60) NOT NULL,
  ISVN_FK NUMBER(8) NOT NULL,
  EMISORA_FK VARCHAR(25) NOT NULL,
  FECHA DATE NOT NULL,
  HORA TIMESTAMP NOT NULL,
  CONSTRAINT PK_EXITOS PRIMARY KEY (TITULO_FK, ISVN_FK, EMISORA_FK, FECHA, HORA),
  CONSTRAINT FK_TEMA FOREIGN KEY(TITULO_FK, ISVN_FK)
  REFERENCES TEMA (TITULO, ISVN_FK),
  CONSTRAINT FK_EMISORA FOREIGN KEY (EMISORA_FK)
  REFERENCES EMISORA
);

CREATE TABLE SINGLE(
  TITULO_FK VARCHAR(60) NOT NULL,
  ISVN_FK NUMBER(8) NOT NULL,
  POSICION NUMBER(3) NOT NULL,
  SEMANAS NUMBER(3) NOT NULL,
  CONSTRAINT PK_SINGLE PRIMARY KEY(TITULO_FK, ISVN_FK),
  CONSTRAINT FK_SINGLE FOREIGN KEY(TITULO_FK, ISVN_FK)
  REFERENCES TEMA ON DELETE CASCADE
);

CREATE TABLE MIEMBRO (
  NOMBRE VARCHAR(50) NOT NULL,
  ROL VARCHAR(15) NOT NULL,
  GRUPO_ART_FK VARCHAR(50) NOT NULL,
  CONSTRAINT PK_MIEMBRO PRIMARY KEY(NOMBRE, ROL, GRUPO_ART_FK),
  CONSTRAINT FK_GRUPO_ART FOREIGN KEY(GRUPO_ART_FK)
  REFERENCES ARTISTA ON DELETE CASCADE
);

CREATE TABLE CLIENTE(
  DNI CHAR(8),
  NOMBRE VARCHAR(50) NOT NULL,
  APELLIDO1 VARCHAR(30) NOT NULL,
  APELLIDO2 VARCHAR(30),
  FECHA_NAC DATE NOT NULL,
  TELEFONO NUMBER(15),
  EMAIL VARCHAR(60),
  DIR VARCHAR(100),
  CONSTRAINT PK_CLIENTE PRIMARY KEY(NOMBRE, APELLIDO1),
  CONSTRAINT DNI_CHK CHECK (DNI > 9999999 AND DNI < 999999999),
  CONSTRAINT UK_TEL_EMI_CLI UNIQUE(TELEFONO),
  CONSTRAINT CHK_EMAIL_VALIDO_CLI CHECK (
    EMAIL LIKE '%@%.%' AND
    EMAIL NOT LIKE '@%' AND
    EMAIL NOT LIKE '%@%@%')
);

CREATE TABLE COMPRA(
  NOMBRE_CLI_FK VARCHAR(50) NOT NULL,
  APELLIDO_CLI_FK VARCHAR(30) NOT NULL,
  FECHA_COMPRA DATE NOT NULL,
  FECHA_ENTREGA DATE,
  CONSTRAINT PK_COMPRA PRIMARY KEY(NOMBRE_CLI_FK, APELLIDO_CLI_FK, FECHA_COMPRA),
  CONSTRAINT FK_CLIENTE FOREIGN KEY(NOMBRE_CLI_FK, APELLIDO_CLI_FK)
  REFERENCES CLIENTE,
  CONSTRAINT CHK_FECHA_COMPRA CHECK (FECHA_COMPRA <= FECHA_ENTREGA)
);

CREATE TABLE REFERENCIA(
  NOMBRE_CLI_FK VARCHAR(50) NOT NULL,
  APELLIDO_CLI_FK VARCHAR(30) NOT NULL,
  FECHA_COMPRA_FK DATE NOT NULL,
  ISVN_FK NUMBER(8) NOT NULL,
  CONSTRAINT PK_REFERENCIA PRIMARY KEY(NOMBRE_CLI_FK, APELLIDO_CLI_FK, FECHA_COMPRA_FK, ISVN_FK),
  CONSTRAINT FK_COMPRA FOREIGN KEY(NOMBRE_CLI_FK, APELLIDO_CLI_FK, FECHA_COMPRA_FK)
  REFERENCES COMPRA (NOMBRE_CLI_FK, APELLIDO_CLI_FK, FECHA_COMPRA) ON DELETE CASCADE,
  CONSTRAINT FK_VINILO FOREIGN KEY(ISVN_FK)
  REFERENCES VINILO ON DELETE CASCADE,
  CONSTRAINT LONG_ISVN  CHECK (ISVN_FK > 9999999)
);
